# Generated by Django 3.0.6 on 2020-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mala',
            name='rfid',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='passageiro',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
