# Generated by Django 3.0.6 on 2020-06-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_cidade_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Cidade')),
            ],
        ),
    ]
