# Generated by Django 3.0.6 on 2020-06-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_aeroporto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aeroporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Aeroporto')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Passageiro')),
            ],
        ),
    ]
